export enum ENV {
  BOT_TOKEN = "BOT_TOKEN",
  SERVER_URL = "SERVER_URL",
  PORT = "PORT",
  NODE_ENV = "NODE_ENV",
  REDIS_DATABASE_URL = "REDIS_DATABASE_URL",
  COPPERX_API_KEY = "COPPERX_API_KEY",
}
